server:
  port: 8765

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    loadbalancer:
      configurations: health-check
      retry:
        enabled: true
      ribbon:
        enabled: false

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s

      routes:
        # --- students-service ---
        - id: students-service
          uri: lb://CONFIG-CLIENT
          predicates:
            - Path=/students/**
          filters:
            - RewritePath=/students/(?<segment>.*), /api/v1/${segment}
            - name: CircuitBreaker
              args:
                name: studentsBreaker
                fallbackuri: forward:/fallback/students

        # --- order-service ---
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /api/v1/${segment}
            - name: CircuitBreaker
              args:
                name: ordersBreaker
                fallbackuri: forward:/fallback/orders

        # --- user-service ---
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/v1/${segment}
            - name: CircuitBreaker
              args:
                name: usersBreaker
                fallbackuri: forward:/fallback/users

# ✅ CORRECT INDENTATION: This is a top-level property
resilience4j:
  circuitbreaker:
    instances:
      studentsBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      
      # ✅ ADDED: Configuration for the order service circuit breaker
      ordersBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      # ✅ ADDED: Configuration for the user service circuit breaker
      usersBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: students
        url: /students/api/v1/v3/api-docs
