server:
  port: 8765

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      routes:
        - id: students-service
          uri: http://localhost:8090     # or lb://STUDENTS if using discovery
          predicates:
            - Path=/students/**
          filters:
            # strips "/students" before forwarding so "/students/v3/api-docs" -> "/v3/api-docs"
            - RewritePath=/students/(?<segment>.*), /${segment}

#  data:
#    redis:
#      host: localhost
#      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html        # UI entrypoint at the gateway
    urls:
      - name: students
        url: /students/v3/api-docs
