server:
  port: 8765

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    loadbalancer:
      configurations: health-check           # only route to healthy instances
      retry:
        enabled: true
      ribbon:
        enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          httpclient:
            connect-timeout: 3000
            response-timeout: 5s
          routes:
            - id: students-service
              uri: lb://CONFIG-CLIENT     # or lb://STUDENTS if using discovery
              predicates:
                - Path=/students/**
              filters:
                # strips "/students" before forwarding so "/students/v3/api-docs" -> "/v3/api-docs"
                - RewritePath=/students/(?<segment>.*), /api/v1/${segment}
                - name: CircuitBreaker
                  args:
                    name: studentsBreaker
                    fallbackUri: forward:/fallback/students
              - id: order-service
                uri: lb://ORDER-SERVICE    # or lb://STUDENTS if using discovery
                predicates:
                  - Path=/orders/**
                filters:
                  # strips "/students" before forwarding so "/students/v3/api-docs" -> "/v3/api-docs"
                  - RewritePath=/orders/(?<segment>.*), /api/v1/${segment}
                  - name: CircuitBreaker
                    args:
                      name: ordersBreaker
                      fallbackUri: forward:/fallback/orders
                - id: user-service
                  uri: lb://USER-SERVICE    # or lb://STUDENTS if using discovery
                  predicates:
                    - Path=/users/**
                  filters:
                    # strips "/students" before forwarding so "/students/v3/api-docs" -> "/v3/api-docs"
                    - RewritePath=/users/(?<segment>.*), /api/v1/${segment}
                    - name: CircuitBreaker
                      args:
                        name: usersBreaker
                        fallbackUri: forward:/fallback/students
      

#  data:
#    redis:
#      host: localhost
#      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html        # UI entrypoint at the gateway
    urls:
      - name: students
        url: /students/v3/api-docs
